import { useEffect, useState } from 'react'
import type { AccountApi } from './AccountSecurity.tsx'
import type { Application } from '../application.ts'
import { ActionForm, AccountSection, ConfirmButton, useAccountData } from './AccountForms.tsx'
import { Button } from './primitives.tsx'
const roleLabels = { owner: '所有者', admin: '管理员', member: '成员' } as const
export function Teams({ api, app }: { api: AccountApi; app: Application }) {
  const teams = useAccountData(() => api.teams(), [api]), [selected, setSelected] = useState('')
  const current = teams.data?.find(team => team.id === selected)
  // A focused/open page must recheck governance after another device changes it.
  useEffect(() => { const reload = () => teams.reload(); window.addEventListener('focus', reload); const timer = window.setInterval(reload, 15000); return () => { window.removeEventListener('focus', reload); window.clearInterval(timer) } }, [api])
  return <><h1>团队与成员</h1><ActionForm label="创建团队" fields={[{ name: 'name', label: '团队名称' }]} submit={async values => { const team = await api.createTeam(values.name!); setSelected(team.id); teams.reload(); return '团队已创建，只有你成为所有者。' }} />{teams.feedback}{teams.data && <><label>查看团队<select value={current?.id ?? ''} onChange={event => setSelected(event.target.value)}><option value="">请选择团队</option>{teams.data.map(team => <option value={team.id} key={team.id}>{team.name}（{roleLabels[team.role]}）</option>)}</select></label>{!teams.data.length && <p>尚未加入团队。</p>}</>}{current && <><Button variant="outline" onClick={() => void app.selectTeam(current.id)}>将此团队设为当前项目范围</Button><TeamMembers key={`${current.id}:${current.role}`} api={api} team={current} reloadTeams={teams.reload} /></>}</>
}
function TeamMembers({ api, team, reloadTeams }: { api: AccountApi; team: Awaited<ReturnType<AccountApi['teams']>>[number]; reloadTeams: () => void }) {
  const members = useAccountData(() => api.teamMembers(team.id), [api, team.id])
  const canManage = team.role !== 'member'
  const reload = () => { members.reload(); reloadTeams() }
  return <><AccountSection title={`${team.name} 成员`}>{members.feedback}{members.data?.map(member => <div className="account-row" key={member.user.id}><p>{member.user.username} {member.user.email}（{roleLabels[member.role]}）</p>{team.role === 'owner' && member.role !== 'owner' && <><ActionForm label={`更新 ${member.user.username} 角色`} confirm="确认修改成员治理角色？权限立即按服务端最新状态判定。" submit={async values => { await api.updateTeamMemberRole(team.id, member.user.id, values.role as 'admin' | 'member'); reload(); return '成员角色已更新。' }}><label>成员角色<select name="role" defaultValue={member.role}><option value="member">成员</option><option value="admin">管理员</option></select></label></ActionForm><ActionForm label={`转让所有权给 ${member.user.username}`} confirm="所有权转让后你的角色会改变，确认继续？" fields={[{ name: 'confirmation', label: `输入团队名称 ${team.name} 确认` }]} submit={async values => { await api.transferTeamOwnership(team.id, member.user.id, values.confirmation!); reload(); return '团队所有权已转让。' }} /></>}{canManage && member.role !== 'owner' && (team.role === 'owner' || member.role === 'member') && <ConfirmButton confirm={`确认移除成员 ${member.user.username}？其团队资源授权将失效。`} act={async () => { await api.removeTeamMember(team.id, member.user.id); reload(); return '成员已移除。' }}>移除成员</ConfirmButton>}</div>)}</AccountSection>{canManage && <TeamInvitations api={api} teamId={team.id} />}</>
}
function TeamInvitations({ api, teamId }: { api: AccountApi; teamId: string }) {
  const invitations = useAccountData(() => api.teamInvitations(teamId), [api, teamId])
  const [link, setLink] = useState('')
  return <AccountSection title="团队邀请"><p>邀请指定邮箱，注册账号与接受邀请是两个独立步骤。重发须先撤销待接受邀请，再签发新邀请。</p><ActionForm label="发送邀请" fields={[{ name: 'email', label: '受邀邮箱', type: 'email' }]} submit={async values => { setLink(''); const invite = await api.inviteTeamMember(teamId, values.email!); setLink(`/next/join?token=${encodeURIComponent(invite.token)}`); invitations.reload(); return '邀请已创建；如实例配置了邮件，将投递给受邀者。' }} />{link && <p>本次邀请：<a href={link}>在新版查看邀请</a><Button variant="ghost" onClick={() => setLink('')}>隐藏链接</Button></p>}{invitations.feedback}{invitations.data?.map(invite => <div className="account-row" key={invite.id}><p>{invite.email}：{({ pending: '待接受', accepted: '已接受', expired: '已过期', revoked: '已撤销' })[invite.status]}，到期 {new Date(invite.expiresAt).toLocaleString('zh-CN')}</p>{invite.status === 'pending' && <ConfirmButton confirm="确认撤销此邀请？" act={async () => { await api.revokeTeamInvitation(teamId, invite.id); invitations.reload(); setLink(''); return '邀请已撤销。' }}>撤销邀请</ConfirmButton>}{invite.status !== 'accepted' && <ConfirmButton confirm="确认重新发送邀请？" act={async () => { setLink(''); try { if (invite.status === 'pending') await api.revokeTeamInvitation(teamId, invite.id); const next = await api.inviteTeamMember(teamId, invite.email); setLink(`/next/join?token=${encodeURIComponent(next.token)}`); return '新邀请已创建。' } finally { invitations.reload() } }}>重发邀请</ConfirmButton>}</div>)}</AccountSection>
}
export function JoinTeam({ api, token, app }: { api: AccountApi; token: string; app: Application }) {
  const invitation = useAccountData(() => api.invitation(token), [api, token])
  return <><h1>接受团队邀请</h1>{invitation.feedback}{invitation.data && <AccountSection title={invitation.data.team.name}><p>受邀邮箱：{invitation.data.email}</p><p>邀请状态：{({ pending: '待接受', accepted: '已接受', expired: '已过期', revoked: '已撤销' })[invitation.data.status]}</p><p>只有受邀邮箱对应的已验证账号可以接受，登录不会自动加入团队。</p><ActionForm label="接受邀请" disabled={invitation.data.status !== 'pending'} submit={async () => { const result = await api.acceptInvitation(token); window.history.replaceState(null, '', '/next/teams'); await app.selectTeam(result.teamId); window.location.assign('/next/teams') }} /></AccountSection>}<a href="/next/teams">返回团队</a></>
}
