export type { AccountSession, AccountPayloadDTO, AccountViewDTO, AuthOptionsDTO, ProjectDTO, HostBootstrap, HostKind, LocalStatus } from '@wemux/web-contract/browser-host'
export { hostContractVersion, discoverHost, parseHostBootstrap } from './bootstrap.ts'
export { ApiError, classifyClientError } from './errors.ts'
export type { ClientErrorKind } from './errors.ts'
export { createClusterTransport } from './cluster-transport.ts'
export type { ClusterTransportOptions, RequestMethod } from './cluster-transport.ts'
export { anonymousSession, isSignedIn, toAccountSession, createClusterClient, clusterAccountOperations } from './cluster-client.ts'
export { createLocalIdentityClient, createLocalTransport, localIdentityOperations } from './local-identity.ts'
export { randomId } from './random.ts'
export { copyText, selectElementText } from './clipboard.ts'
export { taskSessionOperations } from './task-sessions.ts'
export { PendingTaskSession } from './pending-task-session.ts'
export { PendingTaskRun } from './pending-task-run.ts'
export { PendingHumanReview, ReviewVersionConflict } from './pending-human-review.ts'
export { PendingTaskCompletion, CompletionVersionConflict } from './pending-task-completion.ts'
export { PendingHumanDecision, DecisionVersionConflict } from './pending-human-decision.ts'
export { PendingRunCancellation } from './pending-run-cancellation.ts'
export type { RunCancellationScope } from './pending-run-cancellation.ts'
export type { TaskRunIntent, TaskRunScope } from './pending-task-run.ts'
export type { TaskSessionScope, TaskSessionIntent } from './pending-task-session.ts'
export { sessionConversationOperations } from './session-conversation.ts'
export type { ConversationWatch, ConversationWatchOptions } from './session-conversation.ts'
export { createConversationProjection, appendConversationEvents, projectConversationEvents, ConversationProjectionError } from './conversation-projection.ts'
export type { ConversationTextStream, ConversationToolStream, ConversationRuntimeState, ConversationTurnOutcome, ConversationTurnFailure, ConversationUsage, ConversationJournalPayload, ConversationEventOrigin, ConversationTimelineEntry, ConversationMessage, ConversationTurn, ConversationTextSegment, ConversationTool, ConversationApproval, ConversationProjection, ConversationProjectionErrorCode } from './conversation-projection.ts'
export { createConversationController } from './conversation-controller.ts'
export type { ConversationScope, ConversationReadPort, ConversationControllerOptions, ConversationReadError, ConversationSnapshot, ConversationController } from './conversation-controller.ts'
export type { ConversationSession, ConversationFreshness, ConversationEvent, ConversationHistoryPage, SendConversationMessage, ConversationCommandStatus, ConversationSendReceipt, ConversationCommandReceipt } from '@wemux/web-contract'
export { createConversationSubmission } from './conversation-submission.ts'
export type { ConversationSubmissionScope, ConversationSubmissionStorage, ConversationSubmissionOptions, ConversationSubmissionIntent, ConversationSubmissionSnapshot, ConversationSubmissionController } from './conversation-submission.ts'
export type { CancelQueuedConversationMessage, StopConversationTurn, ConversationControlReceipt } from '@wemux/web-contract'
export { createConversationControls } from './conversation-controls.ts'
export type { ConversationControlScope, ConversationControlIntent, ConversationControlStorage, ConversationControlPort, ConversationControlOptions, ConversationControlSnapshot, ConversationControls } from './conversation-controls.ts'
