import test from 'node:test'
import assert from 'node:assert/strict'
import { createLocalSessionApi } from '../src/hosts/local-session.ts'

test('local settings and cluster adapter uses Worker cookie/CSRF and handles 204 leave', async () => {
  const requests = []
  const api = createLocalSessionApi(async (url, init) => {
    requests.push({ url, ...init })
    if (url.endsWith('/status')) return Response.json({ csrf: 'worker-only-csrf', capabilities: [], cluster: { enrolled: false }, installation: { name: 'local', installationId: 'one' } })
    if (url.endsWith('/cluster/enrollment') || url.endsWith('/auth/session')) return new Response(null, { status: 204 })
    if (url.endsWith('/cluster/discover')) return Response.json({ serverUrl: 'https://server.example', ok: true, status: 200 })
    if (url.endsWith('/cluster/enroll')) return Response.json({ identity: { workerId: 'w1' } }, { status: 201 })
    if (url.endsWith('/agents/pi')) return Response.json({ selections: [], capabilities: [] })
    throw new Error(`unexpected URL ${url}`)
  })
  await api.status()
  await api.selectAgent('pi', '/usr/bin/pi')
  assert.equal(requests[1].method, 'PUT')
  assert.deepEqual(JSON.parse(requests[1].body), { executable: '/usr/bin/pi' })
  await api.resetAgent('pi')
  assert.equal(requests[2].method, 'DELETE')
  await api.discoverCluster('https://server.example')
  await api.enrollCluster('https://server.example', 'secret', 'worker')
  assert.deepEqual(JSON.parse(requests[4].body), { serverUrl: 'https://server.example', token: 'secret', name: 'worker' })
  assert.equal(await api.leaveCluster(), undefined)
  assert.equal(await api.logout(), undefined)
  assert.equal(requests[6].url, '/api/local/auth/session')
  assert.equal(requests[6].method, 'DELETE')
  assert.ok(requests.slice(1).every(request => request.headers['x-wemux-csrf'] === 'worker-only-csrf' && request.credentials === 'same-origin'))
  assert.ok(requests.every(request => request.url.startsWith('/api/local/')))
})

test('local adapter writes with Worker CSRF and stable caller message identities', async () => {
  const requests = []
  const api = createLocalSessionApi(async (url, init) => {
    requests.push({ url, ...init })
    if (url.endsWith('/status')) return Response.json({ csrf: 'worker-only-csrf', capabilities: [], installation: { name: 'local', installationId: 'one' } })
    if (url.endsWith('/messages') || url.endsWith('/cancel') || url.endsWith('/resolve')) return Response.json({ commandId: 'cmd', status: 'accepted' }, { status: 202 })
    if (url.endsWith('/journal?fromSeq=1&limit=500')) return Response.json({ events: [], throughSeq: 0, hasMore: false })
    throw new Error(`unexpected URL: ${url}`)
  })
  await api.status()
  const receipt = await api.send('session', '你好', { commandId: 'cmd', messageId: 'msg' })
  assert.deepEqual(receipt, { commandId: 'cmd', messageId: 'msg', status: 'accepted' })
  assert.equal(requests[1].url, '/api/local/workbench/sessions/session/messages')
  assert.equal(requests[1].headers['x-wemux-csrf'], 'worker-only-csrf')
  assert.deepEqual(JSON.parse(requests[1].body), { commandId: 'cmd', messageId: 'msg', content: '你好' })
  assert.equal(requests[1].credentials, 'same-origin')
  await api.journal('session', 1, 500)
  assert.ok(!('x-wemux-csrf' in requests[2].headers))
  await api.cancelQueued('session', 'queued-command')
  assert.equal(requests[3].url, '/api/local/workbench/sessions/session/queue/queued-command/cancel')
  assert.equal(requests[3].method, 'DELETE')
  assert.equal(requests[3].headers['x-wemux-csrf'], 'worker-only-csrf')
  await api.resolveApproval('session', 'approval-1', 'deny', 'stable-command')
  assert.equal(requests[4].url, '/api/local/workbench/sessions/session/approvals/approval-1/resolve')
  assert.equal(requests[4].headers['x-wemux-csrf'], 'worker-only-csrf')
  assert.deepEqual(JSON.parse(requests[4].body), { decision: 'deny', commandId: 'stable-command' })
  assert.ok(requests.every(request => !request.url.startsWith('/api/auth/') && !request.url.startsWith('/api/projects')))
})
