import { readFileSync } from 'node:fs'
import assert from 'node:assert/strict'
import test from 'node:test'
const source = path => readFileSync(new URL(path, import.meta.url), 'utf8')
test('mobile project pages prioritize conversation and keep workspace access directly visible', () => {
  const nav = source('../src/components/project-quick-nav.tsx')
  assert.match(nav, /aria-label="项目快捷导航"/)
  assert.match(nav, /projectNavigationItems\.map/)
  const items = source('../src/components/navigation-items.ts')
  assert.match(items, /path: 'sessions'.*shortLabel: '对话'/)
  assert.match(items, /path: 'workspaces'.*shortLabel: '工作区'/)
  assert.match(items, /path: 'board'.*shortLabel: '任务'/)
  assert.match(nav, /aria-current=/)
  const app = source('../src/App.tsx')
  assert.match(app, /<MainCanvas>.*<ProjectQuickNav/)
  assert.doesNotMatch(app, /setContextOpen\(matchMedia/)
})
test('project routes use API project ids and only load the graph on overview', () => {
  const app = source('../src/App.tsx')
  const navigation = source('../src/features/sessions/navigation.tsx')
  assert.match(app, /onProject=\{id => go\(`\/projects\/\$\{encodeURIComponent\(id\)\}\/sessions`\)\}/)
  assert.match(navigation, /onSelect=\{\(\) => onProject\(item\.id\)\}/)
  assert.doesNotMatch(navigation, /onProject\(item\.name\)/)
  assert.match(app, /enabled: Boolean\(projectId\) && section === 'overview'/)
})

test('project conversation route is a single draft canvas; recent sessions remain contextually accessible', () => {
  const app = source('../src/App.tsx')
  assert.match(app, /section === 'sessions' \? <div className="m-auto w-full">\{quickEntry\}/)
  assert.doesNotMatch(app, /ProjectSessionList/)
  assert.match(app, /workspaceId && sessions.filter/)
  const navigation = source('../src/features/sessions/navigation.tsx')
  assert.match(navigation, /aria-label="新建会话"/)
  assert.match(navigation, /projectNavigationItems\.map/)
  assert.match(navigation, /visibleSessions.map\(session/)
  assert.match(navigation, /onCreate\('session'\)/)
})
test('overview exposes readable recent sessions and existing workspaces', () => {
  const resources = source('../src/components/project-resources.tsx')
  assert.match(resources, /aria-label="工作区快捷入口"/)
  assert.match(resources, /aria-label="最近会话"/)
  assert.match(resources, /filter\(item => item.canRead\)/)
  assert.match(resources, /sort\(\(a, b\) => b.updatedAt.localeCompare\(a.updatedAt\)\)/)
  assert.match(resources, /workspaces\/\$\{encodeURIComponent\(ws.id\)\}/)
  assert.match(resources, /sessions\/\$\{encodeURIComponent\(session.id\)\}/)
  assert.match(source('../src/App.tsx'), /<ProjectResources.*<ProjectOverview/)
})
