import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { HttpConnectorDefinition } from '@wemux/connector'
import { WorkerConnectorRuntime } from '../worker/src/connectors/runtime.ts'
import { SqliteWorkerStore } from '../worker/src/storage/sqlite-store.ts'

const timestamp='2026-01-01T00:00:00.000Z'
const definition:HttpConnectorDefinition={id:'connector-1' as never,projectId:'project-1' as never,name:'Fixture',description:null,revision:1,enabled:true,allowedWorkerIds:[],credentialRef:'fixture-key' as never,credentialAvailability:'unconfigured',riskDefaults:{requireApprovalForRead:false,allowMcpReadOnlyHint:false},createdAt:timestamp,updatedAt:timestamp,kind:'http',config:{baseUrl:'https://fixture.example',authentication:'api_key',publicHeaders:{},allowedOperations:[{id:'health',method:'GET',pathTemplate:'/health',allowedQueryNames:[],allowedRequestHeaderNames:[],requestContentTypes:[]}],allowPrivateNetwork:false}}

test('Server revision to Worker credential test and safe HTTP execution',async()=>{const dir=await mkdtemp(join(tmpdir(),'wemux-connector-e2e-'));const store=new SqliteWorkerStore(join(dir,'worker.sqlite'));let observed='';const runtime=new WorkerConnectorRuntime(store,{fetch:(async(input,init)=>{const request=new Request(input,init);observed=request.headers.get('authorization')??'';return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch,lookup:async()=>[{address:'8.8.8.8',family:4}]});try{assert.equal((await runtime.syncClusterDefinition(definition,'worker-1')).status,'unavailable');assert.equal((await runtime.testClusterDefinition(definition.id,1)).status,'test_failed');const unavailable=runtime.credentials;assert.equal(unavailable.available,false);const keyed=new (await import('../worker/src/connectors/credential-store.ts')).WorkerCredentialStore(store,{key:'e2e-key'});await keyed.put({id:'fixture-key' as never,connectorId:definition.id,authType:'api_key',secret:{value:'e2e-secret-value'}});const executor=new (await import('../worker/src/connectors/http-executor.ts')).HttpConnectorExecutor(keyed,{fetch:(async(input,init)=>{const request=new Request(input,init);observed=request.headers.get('authorization')??'';return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch,lookup:async()=>[{address:'8.8.8.8',family:4}]});const result=await executor.execute(definition,{operationId:'health'});assert.equal(observed,'Bearer e2e-secret-value');assert.doesNotMatch(JSON.stringify(result.journalSummary),/e2e-secret-value/);await store.deleteConnectorDefinition(definition.id);assert.equal(await store.getConnectorDefinition(definition.id),null)}finally{await runtime.shutdown();await store.close();await rm(dir,{recursive:true,force:true})}})
