import { DatabaseSync } from 'node:sqlite'
import type { ProjectId, SessionId, Timestamp } from '@wemux/domain'
import type { Channel, ChannelBindingId, ChannelId } from '@wemux/connector'
import type { InboundDelivery, OutboundDelivery } from '@wemux/server-domain'
import { migrate } from './migrations.ts'
import type { AcceptInboundInput, AcceptInboundResult, ChannelBindingRecord, ChannelRepository, ChannelRequestRecord, ChannelSecretRecord } from '../../application/ports/channel-repository.ts'

export class SqliteChannelRepository implements ChannelRepository {
  private queue: Promise<unknown> = Promise.resolve()
  private readonly db: DatabaseSync
  constructor(path: string) { this.db = new DatabaseSync(path); this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;'); migrate(this.db) }
  close(): void { this.db.close() }
  private serial<T>(work: () => T): Promise<T> { const result = this.queue.then(work); this.queue = result.catch(() => undefined); return result }
  private transaction<T>(work: () => T): T { this.db.exec('BEGIN IMMEDIATE'); try { const result = work(); this.db.exec('COMMIT'); return result } catch (error) { this.db.exec('ROLLBACK'); throw error } }

  getChannel(id: ChannelId): Promise<Channel | null> { return this.serial(() => this.channel(this.db.prepare('SELECT data FROM channel_definitions WHERE id=?').get(id))) }
  listChannels(projectId: ProjectId): Promise<readonly Channel[]> { return this.serial(() => this.db.prepare('SELECT data FROM channel_definitions WHERE project_id=? ORDER BY id').all(projectId).map(row => JSON.parse(String(row.data)) as Channel)) }
  getSecret(channelId: ChannelId): Promise<ChannelSecretRecord | null> { return this.serial(() => { const row = this.db.prepare('SELECT * FROM channel_secrets WHERE channel_id=?').get(channelId); return row ? { credentialId: String(row.credential_id) as never, channelId: String(row.channel_id) as ChannelId, ciphertext: String(row.ciphertext), revision: Number(row.revision), createdAt: String(row.created_at) as Timestamp, updatedAt: String(row.updated_at) as Timestamp } : null }) }
  getRequest(projectId: ProjectId, requestId: string): Promise<ChannelRequestRecord | null> { return this.serial(() => { const row = this.db.prepare('SELECT * FROM channel_requests WHERE project_id=? AND request_id=?').get(projectId, requestId); return row ? this.request(row) : null }) }
  channelCallbackUrl(channelId: ChannelId): Promise<string | null> { return this.serial(() => { const row = this.db.prepare('SELECT callback_url FROM channel_definitions WHERE id=?').get(channelId); return row?.callback_url === null || row?.callback_url === undefined ? null : String(row.callback_url) }) }

  createChannel(channel: Channel, secret: ChannelSecretRecord, callbackUrl: string | null, request: ChannelRequestRecord): Promise<void> { return this.serial(() => this.transaction(() => { this.db.prepare('INSERT INTO channel_definitions VALUES(?,?,?,?,?,?)').run(channel.id, channel.projectId, channel.revision, channel.enabled ? 1 : 0, callbackUrl, JSON.stringify(channel)); this.db.prepare('INSERT INTO channel_secrets VALUES(?,?,?,?,?,?)').run(secret.credentialId, secret.channelId, secret.revision, secret.ciphertext, secret.createdAt, secret.updatedAt); this.insertRequest(request) })) }
  updateChannel(channel: Channel, expectedRevision: number, request: ChannelRequestRecord, cancelPending = false): Promise<boolean> { return this.serial(() => this.transaction(() => { const changed = this.db.prepare('UPDATE channel_definitions SET revision=?,enabled=?,data=? WHERE id=? AND project_id=? AND revision=?').run(channel.revision, channel.enabled ? 1 : 0, JSON.stringify(channel), channel.id, channel.projectId, expectedRevision).changes === 1; if (changed) { if (cancelPending) this.cancelPending(channel.id, channel.updatedAt); this.insertRequest(request) } return changed })) }

  getBinding(id: ChannelBindingId): Promise<ChannelBindingRecord | null> { return this.serial(() => this.binding(this.db.prepare('SELECT * FROM channel_bindings WHERE id=?').get(id))) }
  findBinding(channelId: ChannelId, externalConversationKey: string): Promise<ChannelBindingRecord | null> { return this.serial(() => this.binding(this.db.prepare('SELECT * FROM channel_bindings WHERE channel_id=? AND external_conversation_key=?').get(channelId, externalConversationKey))) }
  listBindings(projectId: ProjectId, channelId?: ChannelId): Promise<readonly ChannelBindingRecord[]> { return this.serial(() => (channelId ? this.db.prepare('SELECT * FROM channel_bindings WHERE project_id=? AND channel_id=? ORDER BY id').all(projectId, channelId) : this.db.prepare('SELECT * FROM channel_bindings WHERE project_id=? ORDER BY id').all(projectId)).map(row => this.binding(row)!)) }
  createBinding(record: ChannelBindingRecord, request: ChannelRequestRecord): Promise<void> { return this.serial(() => this.transaction(() => { const b = record.binding; this.db.prepare('INSERT INTO channel_bindings VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b.id, b.projectId, b.channelId, b.externalConversationKey, b.sessionId, b.workerId, b.revision, b.enabled ? 1 : 0, record.callbackUrl, record.createdBy, JSON.stringify(b)); this.insertRequest(request) })) }
  updateBinding(record: ChannelBindingRecord, expectedRevision: number, request: ChannelRequestRecord): Promise<boolean> { return this.serial(() => this.transaction(() => { const b = record.binding; const changed = this.db.prepare('UPDATE channel_bindings SET revision=?,enabled=?,callback_url=?,data=? WHERE id=? AND project_id=? AND revision=?').run(b.revision, b.enabled ? 1 : 0, record.callbackUrl, JSON.stringify(b), b.id, b.projectId, expectedRevision).changes === 1; if (changed) this.insertRequest(request); return changed })) }

  acceptInbound(input: AcceptInboundInput): Promise<AcceptInboundResult> { return this.serial(() => this.transaction(() => { const d = input.delivery; const existing = this.db.prepare('SELECT data,fingerprint FROM channel_inbound_deliveries WHERE channel_id=? AND provider_event_id=?').get(d.channelId, d.providerEventId); if (existing) { const delivery = JSON.parse(String(existing.data)) as InboundDelivery; return String(existing.fingerprint) === d.fingerprint ? { kind: 'duplicate', delivery } : { kind: 'conflict', delivery } } this.db.prepare('INSERT INTO channel_inbound_deliveries VALUES(?,?,?,?,?,?,?,?,?,?)').run(d.id, d.channelId, d.projectId, d.providerEventId, d.fingerprint, d.status, d.sessionEnqueueRequestId, d.receivedAt, d.updatedAt, JSON.stringify(d)); return { kind: 'accepted', delivery: d } })) }
  claimAcceptedInbound(limit: number): Promise<readonly InboundDelivery[]> { return this.serial(() => this.transaction(() => { const rows = this.db.prepare("SELECT data FROM channel_inbound_deliveries WHERE status='accepted' ORDER BY received_at LIMIT ?").all(limit); const values = rows.map(row => JSON.parse(String(row.data)) as InboundDelivery); for (const value of values) { const next = { ...value, status: 'routing' as const, updatedAt: new Date().toISOString() as Timestamp }; this.writeInbound(next) } return values.map(value => ({ ...value, status: 'routing' as const })) })) }
  updateInbound(delivery: InboundDelivery): Promise<void> { return this.serial(() => { this.writeInbound(delivery) }) }
  listInbound(projectId: ProjectId, limit: number): Promise<readonly InboundDelivery[]> { return this.serial(() => this.db.prepare('SELECT data FROM channel_inbound_deliveries WHERE project_id=? ORDER BY received_at DESC LIMIT ?').all(projectId, limit).map(row => JSON.parse(String(row.data)) as InboundDelivery)) }
  findInboundBySessionRequest(sessionId: SessionId, requestId: string): Promise<InboundDelivery | null> { return this.serial(() => { const row = this.db.prepare('SELECT data FROM channel_inbound_deliveries WHERE session_request_id=? AND json_extract(data,\'$.sessionId\')=?').get(requestId, sessionId); return row ? JSON.parse(String(row.data)) as InboundDelivery : null }) }

  saveOutbound(delivery: OutboundDelivery): Promise<boolean> { return this.serial(() => this.db.prepare('INSERT OR IGNORE INTO channel_outbound_deliveries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(delivery.id, delivery.channelId, delivery.bindingId, delivery.projectId, delivery.sessionId, delivery.journalEventIdentity, delivery.status, delivery.attempt, delivery.nextAttemptAt, delivery.leaseExpiresAt, delivery.createdAt, delivery.updatedAt, JSON.stringify(delivery)).changes === 1) }
  getOutbound(id: string): Promise<OutboundDelivery | null> { return this.serial(() => { const row = this.db.prepare('SELECT data FROM channel_outbound_deliveries WHERE id=?').get(id); return row ? JSON.parse(String(row.data)) as OutboundDelivery : null }) }
  listOutbound(projectId: ProjectId, limit: number): Promise<readonly OutboundDelivery[]> { return this.serial(() => this.db.prepare('SELECT data FROM channel_outbound_deliveries WHERE project_id=? ORDER BY created_at DESC LIMIT ?').all(projectId, limit).map(row => JSON.parse(String(row.data)) as OutboundDelivery)) }
  claimOutbound(now: Timestamp, leaseUntil: Timestamp, limit: number): Promise<readonly OutboundDelivery[]> { return this.serial(() => this.transaction(() => { const rows = this.db.prepare(`SELECT data FROM channel_outbound_deliveries WHERE (status='pending' OR (status='retry_wait' AND next_attempt_at<=?) OR (status='sending' AND lease_expires_at<=?)) ORDER BY created_at LIMIT ?`).all(now, now, limit); const claimed: OutboundDelivery[] = []; for (const row of rows) { const value = JSON.parse(String(row.data)) as OutboundDelivery; const next = { ...value, status: 'sending' as const, attempt: value.attempt + 1, leaseExpiresAt: leaseUntil, nextAttemptAt: null, updatedAt: now }; this.writeOutbound(next); claimed.push(next) } return claimed })) }
  updateOutbound(delivery: OutboundDelivery): Promise<void> { return this.serial(() => { this.writeOutbound(delivery) }) }
  cancelPendingForChannel(channelId: ChannelId, updatedAt: Timestamp): Promise<number> { return this.serial(() => this.transaction(() => this.cancelPending(channelId, updatedAt))) }
  replayOutbound(id: string, now: Timestamp, request: ChannelRequestRecord): Promise<OutboundDelivery | null> { return this.serial(() => this.transaction(() => { const row = this.db.prepare('SELECT data FROM channel_outbound_deliveries WHERE id=?').get(id); if (!row) return null; const value = JSON.parse(String(row.data)) as OutboundDelivery; const next = { ...value, status: 'pending' as const, nextAttemptAt: now, leaseExpiresAt: null, diagnostic: '管理员重放', updatedAt: now }; this.writeOutbound(next); this.insertRequest(request); return next })) }

  private channel(row: Record<string, unknown> | undefined): Channel | null { return row ? JSON.parse(String(row.data)) as Channel : null }
  private binding(row: Record<string, unknown> | undefined): ChannelBindingRecord | null { return row ? { binding: JSON.parse(String(row.data)), callbackUrl: String(row.callback_url), createdBy: String(row.created_by) as never } : null }
  private request(row: Record<string, unknown>): ChannelRequestRecord { return { projectId: String(row.project_id) as ProjectId, requestId: String(row.request_id), fingerprint: String(row.fingerprint), operation: String(row.operation) as ChannelRequestRecord['operation'], result: JSON.parse(String(row.result)), createdAt: String(row.created_at) as Timestamp } }
  private insertRequest(value: ChannelRequestRecord): void { this.db.prepare('INSERT INTO channel_requests VALUES(?,?,?,?,?,?)').run(value.projectId, value.requestId, value.fingerprint, value.operation, JSON.stringify(value.result), value.createdAt) }
  private writeInbound(value: InboundDelivery): void { this.db.prepare('UPDATE channel_inbound_deliveries SET status=?,updated_at=?,data=? WHERE id=?').run(value.status, value.updatedAt, JSON.stringify(value), value.id) }
  private writeOutbound(value: OutboundDelivery): void { this.db.prepare('UPDATE channel_outbound_deliveries SET status=?,attempt=?,next_attempt_at=?,lease_expires_at=?,updated_at=?,data=? WHERE id=?').run(value.status, value.attempt, value.nextAttemptAt, value.leaseExpiresAt, value.updatedAt, JSON.stringify(value), value.id) }
  private cancelPending(channelId: ChannelId, updatedAt: Timestamp): number { const rows = this.db.prepare("SELECT data FROM channel_outbound_deliveries WHERE channel_id=? AND status IN ('pending','retry_wait')").all(channelId); for (const row of rows) { const value = JSON.parse(String(row.data)) as OutboundDelivery; this.writeOutbound({ ...value, status: 'cancelled', nextAttemptAt: null, leaseExpiresAt: null, diagnostic: 'Channel 已停用', updatedAt }) } return rows.length }
  private writeRequest(_value: ChannelRequestRecord): void {}
}
