import test from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'
import { launchAcceptanceBrowser } from '../../../tests/acceptance-runtime.mjs'

// Isolated real React component behavior; not full application/server browser acceptance.
test('Attention cursor paging, authorization and response lifetimes', async t => {
  const bundle = await build({
    stdin: { contents: `
      import React from 'react';
      import { createRoot } from 'react-dom/client';
      import { flushSync } from 'react-dom';
      import { Attention } from './Attention.tsx';
      window.requests = []; window.approvalRequests = []; window.legacyCalls = 0;
      const clients = new Map();
      function client(id) {
        if (!clients.has(id)) clients.set(id, {
          attention() { window.legacyCalls++; throw Error('unbounded attention forbidden'); },
          attentionPages(query, signal) { if (query.kind === 'approval') { if (id !== 'approvals') return Promise.resolve({ items: [], nextCursor: null }); return new Promise((resolve, reject) => window.approvalRequests.push({ id, query, signal, resolve, reject })); } return new Promise((resolve, reject) => window.requests.push({ id, query, signal, resolve, reject })); }
        });
        return clients.get(id);
      }
      const root = createRoot(document.getElementById('root'));
      window.renderAttention = (id = 'a', projectIds = ['p'], busy = false, accessRole = 'owner', administrator = true) => flushSync(() => root.render(<Attention api={client(id)} projects={projectIds.map(id => ({ id, accessRole }))} busy={busy} administrator={administrator} />));
      // App replaces Attention with Failure/Login when access verification fails.
      window.failAuthorization = () => flushSync(() => root.render(<p role="alert">权限核验失败</p>));
    `, resolveDir: fileURLToPath(new URL('../', import.meta.url)), loader: 'tsx' },
    bundle: true, write: false, platform: 'browser', format: 'esm', jsx: 'automatic',
  })
  const server = createServer((req, res) => {
    res.setHeader('Content-Type', req.url === '/component.js' ? 'text/javascript' : 'text/html')
    res.end(req.url === '/component.js' ? bundle.outputFiles[0].text : '<div id="root"></div><script type="module" src="/component.js"></script>')
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  let browser
  try {
    browser = await launchAcceptanceBrowser()
    const page = await browser.newPage()
    page.setDefaultTimeout(5000)
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(`http://127.0.0.1:${server.address().port}`)
    await page.waitForFunction(() => typeof window.renderAttention === 'function')
    const mount = (id = 'a', projects = ['p'], busy = false, accessRole = 'owner', administrator = true) => page.evaluate(({ id, projects, busy, accessRole, administrator }) => window.renderAttention(id, projects, busy, accessRole, administrator), { id, projects, busy, accessRole, administrator })
    const waitCalls = count => page.waitForFunction(count => window.requests.length === count, count)
    const reply = (index, keys = [], cursor = null) => page.evaluate(({ index, keys, cursor }) => window.requests[index].resolve({ items: keys.map(key => ({ projectionKey: key, projectId: key.startsWith('hidden') ? 'hidden' : 'p', title: key, detail: 'details', href: '/next/projects/p?task=t&run=' + key })), nextCursor: cursor, generatedAt: '2026-06-01T00:00:00Z' }), { index, keys, cursor })
    const fail = index => page.evaluate(index => window.requests[index].reject(Error('synthetic page failure')), index)
    const runs = page.getByRole('region', { name: '执行异常', exact: true })
    const dead = page.getByRole('region', { name: '渠道投递失败', exact: true })

    await t.test('waits for authorization, bounds requests, filters projects and labels limitations', async () => {
      await mount('a', ['p'], true)
      assert.equal(await page.evaluate(() => window.requests.length), 0)
      await mount()
      await waitCalls(2)
      assert.deepEqual(await page.evaluate(() => window.requests.map(r => r.query)), [{ kind: 'run_problem', limit: 50 }, { kind: 'channel_dead_letter', limit: 50 }])
      await reply(0, ['run-one', 'hidden-run'], 'cursor-1')
      await reply(1, ['dead-one'], 'dead-cursor')
      await runs.getByRole('heading', { name: '执行异常（已加载 1 项）', exact: true }).waitFor()
      assert.equal(await page.getByText('hidden-run', { exact: true }).count(), 0)
      assert.match(await page.locator('#root').innerText(), /会话工具审批未在此页加载.*任务指派尚无人工指派模型/)
      assert.equal(await page.evaluate(() => window.requests.length), 2)
    })
    await t.test('explicit per-group continuation locks duplicate clicks and preserves retry cursor', async () => {
      await runs.getByRole('button', { name: '加载更多执行异常' }).evaluate(button => { button.click(); button.click() })
      await waitCalls(3)
      assert.equal(await page.evaluate(() => window.requests[2].query.cursor), 'cursor-1')
      assert.equal(await runs.getByRole('button').isDisabled(), true)
      await fail(2)
      await runs.getByRole('alert').waitFor()
      assert.equal(await runs.getByRole('link', { name: 'run-one', exact: true }).count(), 1)
      await runs.getByRole('button', { name: '重试执行异常' }).click()
      await waitCalls(4)
      assert.equal(await page.evaluate(() => window.requests[3].query.cursor), 'cursor-1')
      await reply(3, ['run-one', 'run-two', 'run-two'], null)
      await runs.getByRole('heading', { name: '执行异常（已加载 2 项）', exact: true }).waitFor()
      assert.equal(await runs.getByRole('link').count(), 2)
      assert.equal(await runs.getByRole('button').count(), 0)
      await dead.getByRole('button', { name: '加载更多渠道投递失败' }).click()
      await waitCalls(5)
      assert.equal(await page.evaluate(() => window.requests[4].query.cursor), 'dead-cursor')
      await reply(4, [], null)
    })
    await t.test('refresh resets pages and API replacement discards prior data and late responses', async () => {
      await page.getByRole('button', { name: '刷新待办' }).click()
      await waitCalls(7)
      assert.equal(await runs.getByRole('link').count(), 0)
      await mount('b')
      await waitCalls(9)
      assert.equal(await page.evaluate(() => window.requests.slice(5, 7).every(r => r.signal.aborted)), true)
      await reply(5, ['stale-refresh'])
      await fail(6)
      await reply(7, ['new-account'])
      await reply(8)
      await runs.getByRole('link', { name: 'new-account', exact: true }).waitFor()
      assert.equal(await page.getByText('stale-refresh', { exact: true }).count(), 0)
      assert.equal(await page.getByRole('alert').count(), 0)
      assert.equal(await page.evaluate(() => window.requests[7].query.cursor), undefined)
    })
    await t.test('project changes and permission loading hide old data, abort requests and never auto-drain filtered pages', async () => {
      await mount('b', ['other'])
      await waitCalls(11)
      assert.equal(await page.getByRole('link', { name: 'new-account', exact: true }).count(), 0)
      await reply(9, ['p-not-visible'], 'filtered-page')
      await reply(10)
      await runs.getByRole('button', { name: '加载更多执行异常' }).waitFor()
      assert.equal(await runs.getByRole('link').count(), 0)
      assert.equal(await page.evaluate(() => window.requests.length), 11)
      await runs.getByRole('button').click()
      await waitCalls(12)
      await mount('b', ['other'], true)
      assert.equal(await page.evaluate(() => window.requests[11].signal.aborted), true)
      await reply(11, ['late-hidden'])
      assert.equal(await page.getByRole('link').count(), 0)
      await mount('b', [], false)
      await runs.getByText('已加载范围内暂无待办。', { exact: true }).waitFor()
      assert.equal(await page.evaluate(() => window.requests.length), 12)
    })
    await t.test('initial failure is retryable without reporting an empty group', async () => {
      await mount('c')
      await waitCalls(14)
      await fail(12)
      await reply(13)
      await runs.getByRole('alert').waitFor()
      assert.equal(await runs.getByText('已加载范围内暂无待办。', { exact: true }).count(), 0)
      await runs.getByRole('button', { name: '重试执行异常' }).click()
      await waitCalls(15)
      assert.equal(await page.evaluate(() => window.requests[14].query.cursor), undefined)
      await reply(14)
      await runs.getByText('已加载范围内暂无待办。', { exact: true }).waitFor()
    })
    await t.test('App empty-project busy rechecks preserve multiple pages and cursor, suspending pending continuation', async () => {
      const start = await page.evaluate(() => window.requests.length)
      await mount('recheck', ['p', 'other'])
      await waitCalls(start + 2)
      await reply(start, ['page-one'], 'page-two-cursor')
      await reply(start + 1, ['dead-preserved'], 'dead-preserved-cursor')
      await runs.getByRole('button', { name: '加载更多执行异常' }).click()
      await waitCalls(start + 3)
      await reply(start + 2, ['page-two'], 'page-three-cursor')
      await runs.getByRole('heading', { name: '执行异常（已加载 2 项）', exact: true }).waitFor()
      await runs.getByRole('button', { name: '加载更多执行异常' }).click()
      await waitCalls(start + 4)
      await mount('recheck', [], true)
      assert.equal(await page.evaluate(index => window.requests[index].signal.aborted, start + 3), true)
      assert.equal(await page.getByRole('link').count(), 0)
      assert.equal(await page.locator('[hidden][inert]').count(), 1)
      assert.equal(await page.locator('[hidden][inert] a').count(), 3)
      assert.equal(await page.evaluate(() => window.requests.length), start + 4)
      assert.equal(await page.getByRole('button', { name: '刷新待办' }).isDisabled(), true)
      await reply(start + 3, ['aborted-page'], null)
      await mount('recheck', ['other', 'p'])
      await runs.getByRole('heading', { name: '执行异常（已加载 2 项）', exact: true }).waitFor()
      assert.equal(await page.evaluate(() => window.requests.length), start + 4)
      assert.equal(await page.getByText('aborted-page', { exact: true }).count(), 0)
      await dead.getByRole('link', { name: 'dead-preserved', exact: true }).waitFor()
      await runs.getByRole('button', { name: '加载更多执行异常' }).click()
      await waitCalls(start + 5)
      assert.equal(await page.evaluate(index => window.requests[index].query.cursor, start + 4), 'page-three-cursor')
      await reply(start + 4, ['page-three'])
      await runs.getByRole('heading', { name: '执行异常（已加载 3 项）', exact: true }).waitFor()
      await mount('recheck', [], true)
      await mount('recheck', ['p', 'other'])
      await runs.getByRole('heading', { name: '执行异常（已加载 3 项）', exact: true }).waitFor()
      assert.equal(await page.evaluate(() => window.requests.length), start + 5)
      assert.equal(await runs.getByRole('button').count(), 0)
    })
    await t.test('role changes retire pages even when project ids stay the same', async () => {
      const start = await page.evaluate(() => window.requests.length)
      await mount('recheck', [], true)
      await mount('recheck', ['p', 'other'], false, 'viewer')
      await waitCalls(start + 2)
      assert.equal(await page.getByRole('link').count(), 0)
      assert.equal(await page.evaluate(index => window.requests[index].query.cursor, start), undefined)
      await reply(start, ['viewer-page'], 'viewer-cursor')
      await reply(start + 1)
      await runs.getByRole('link', { name: 'viewer-page', exact: true }).waitFor()
    })
    await t.test('failed authorization retires preserved pages and rejects late responses on remount', async () => {
      const start = await page.evaluate(() => window.requests.length)
      await runs.getByRole('button', { name: '加载更多执行异常' }).click()
      await waitCalls(start + 1)
      await mount('recheck', [], true, 'viewer')
      await page.evaluate(() => window.failAuthorization())
      assert.equal(await page.evaluate(index => window.requests[index].signal.aborted, start), true)
      await reply(start, ['late-unauthorized'])
      assert.equal(await page.getByRole('link').count(), 0)
      assert.equal(await page.getByText('viewer-page', { exact: true }).count(), 0)
      await mount('recheck', ['p', 'other'], false, 'viewer')
      await waitCalls(start + 3)
      assert.equal(await page.evaluate(index => window.requests[index].query.cursor, start + 1), undefined)
      await reply(start + 1)
      await reply(start + 2)
      await runs.getByText('已加载范围内暂无待办。', { exact: true }).waitFor()
      assert.equal(await page.getByRole('link').count(), 0)
    })
    await t.test('changed and revoked project grants retire confirmed pages after an empty-project busy recheck', async () => {
      const start = await page.evaluate(() => window.requests.length)
      await mount('grants', ['p', 'other'])
      await waitCalls(start + 2)
      await reply(start, ['before-grant-change'], 'old-grant-cursor')
      await reply(start + 1)
      await runs.getByRole('link', { name: 'before-grant-change', exact: true }).waitFor()
      await mount('grants', [], true)
      assert.equal(await page.locator('[hidden][inert] a').count(), 1)
      await mount('grants', ['p'])
      await waitCalls(start + 4)
      assert.equal(await page.getByText('before-grant-change', { exact: true }).count(), 0)
      assert.equal(await page.evaluate(index => window.requests[index].query.cursor, start + 2), undefined)
      await reply(start + 2, ['remaining-grant'], 'remaining-cursor')
      await reply(start + 3)
      await runs.getByRole('link', { name: 'remaining-grant', exact: true }).waitFor()
      await runs.getByRole('button', { name: '加载更多执行异常' }).click()
      await waitCalls(start + 5)
      await mount('grants', [], true)
      assert.equal(await page.evaluate(index => window.requests[index].signal.aborted, start + 4), true)
      await mount('grants', [])
      await reply(start + 4, ['late-revoked'])
      await runs.getByText('已加载范围内暂无待办。', { exact: true }).waitFor()
      assert.equal(await page.locator('#root a').count(), 0)
      assert.equal(await page.evaluate(() => window.requests.length), start + 5)
    })
    await t.test('human approval group pages, retries and navigates to the Task surface without claiming decision authority', async () => {
      await mount('approvals')
      const approvals = page.getByRole('region', { name: '任务人工审查', exact: true })
      await page.waitForFunction(() => window.approvalRequests.length === 1)
      await page.evaluate(() => window.approvalRequests[0].resolve({ items: [
        { projectionKey: 'approval:review', projectId: 'p', title: '真实任务审查', detail: '任务成果等待人工审查', href: '/next/projects/p?task=review-task' },
        { projectionKey: 'hidden', projectId: 'hidden', title: '不可见审查', href: '/next/projects/hidden' },
      ], nextCursor: 'review-cursor' }))
      await approvals.getByRole('link', { name: '真实任务审查' }).waitFor()
      assert.equal(await approvals.getByText('不可见审查').count(), 0)
      assert.equal(await approvals.getByRole('button', { name: '批准并完成' }).count(), 0)
      await approvals.getByRole('link', { name: '真实任务审查' }).click()
      assert.equal(new URL(page.url()).pathname, '/next/projects/p')
      assert.equal(new URL(page.url()).searchParams.get('task'), 'review-task')
      await approvals.getByRole('button', { name: '加载更多任务人工审查' }).click()
      await page.waitForFunction(() => window.approvalRequests.length === 2)
      assert.equal(await page.evaluate(() => window.approvalRequests[1].query.cursor), 'review-cursor')
      await page.evaluate(() => window.approvalRequests[1].reject(Error('review request failed')))
      await approvals.getByRole('button', { name: '重试任务人工审查' }).click()
      await page.waitForFunction(() => window.approvalRequests.length === 3)
      await mount('different-account')
      assert.equal(await page.evaluate(() => window.approvalRequests[2].signal.aborted), true)
      await page.evaluate(() => window.approvalRequests[2].resolve({ items: [{ projectionKey: 'late', projectId: 'p', title: '旧身份审查', href: '/' }], nextCursor: null }))
      assert.equal(await page.getByText('旧身份审查').count(), 0)
      assert.equal(await page.getByText('真实任务审查', { exact: true }).count(), 0)
    })
    await t.test('non-administrators never request channel dead letters and see an explicit limitation instead', async () => {
      const before = await page.evaluate(() => window.requests.length)
      await mount('nonadmin', ['p'], false, 'owner', false)
      await waitCalls(before + 1)
      assert.deepEqual(await page.evaluate(({ before }) => window.requests.slice(before).map(r => r.query.kind), { before }), ['run_problem'])
      await dead.getByText('渠道死信仅实例管理员可处理，当前账号不是实例管理员。', { exact: true }).waitFor()
      assert.equal(await dead.getByRole('button').count(), 0)
      assert.equal(await dead.getByRole('status').count(), 0)
      await reply(before)
      await runs.getByText('已加载范围内暂无待办。', { exact: true }).waitFor()
    })
    assert.equal(await page.evaluate(() => window.legacyCalls), 0)
    assert.deepEqual(errors, [])
  } finally {
    await browser?.close()
    await new Promise((resolve, reject) => server.close(error => error ? reject(error) : resolve()))
  }
})
