import type { ProjectId } from '@wemux/domain'
import type { ChannelBindingId, ChannelId } from '@wemux/connector'
import { stableFingerprint } from '@wemux/connector'
import { AppError } from '../../application/errors.ts'
import type { RouteDescriptor, RouteRequestContext } from './types.ts'

const service = (context: RouteRequestContext) => { if (!context.channels) throw new AppError(404, 'Not found'); return context.channels }
const input = async (context: RouteRequestContext): Promise<Record<string, unknown>> => { const value = await context.readBody(); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new AppError(400, 'Invalid request body'); return value as Record<string, unknown> }
const requestId = (body: Record<string, unknown>): string => { if (typeof body.requestId !== 'string' || !body.requestId || Buffer.byteLength(body.requestId) > 200) throw new AppError(400, 'Invalid requestId'); return body.requestId }
const fingerprint = (value: unknown): string => stableFingerprint(value)
const revision = (body: Record<string, unknown>): number => { if (!Number.isSafeInteger(body.expectedRevision) || Number(body.expectedRevision) < 1) throw new AppError(400, 'Invalid expectedRevision'); return Number(body.expectedRevision) }
const strings = (value: unknown, field: string): string[] => { if (!Array.isArray(value) || value.some(item => typeof item !== 'string')) throw new AppError(400, `Invalid ${field}`); return value as string[] }

export const channelRoutes: readonly RouteDescriptor[] = [
  { method: 'GET', pattern: '/projects/:projectId/channels', auth: 'authenticated', handler: async context => { const actor = await context.actor('read'), projectId = context.params.projectId as ProjectId; context.json(200, { items: await service(context).list(actor, projectId), bindings: await service(context).bindings(actor, projectId), ...await service(context).deliveries(actor, projectId) }) } },
  { method: 'POST', pattern: '/projects/:projectId/channels', auth: 'authenticated', handler: async context => { const body = await input(context), value = { operation: 'create', name: body.name, callbackUrl: body.callbackUrl ?? null, sourceCidrs: body.sourceCidrs ?? [] }; context.json(201, await service(context).create(await context.actor('write'), { projectId: context.params.projectId as ProjectId, requestId: requestId(body), fingerprint: fingerprint(value), name: String(body.name ?? ''), callbackUrl: body.callbackUrl === null || body.callbackUrl === undefined ? null : String(body.callbackUrl), sourceCidrs: strings(body.sourceCidrs ?? [], 'sourceCidrs') })) } },
  { method: 'POST', pattern: '/projects/:projectId/channels/:channelId/enabled', auth: 'authenticated', handler: async context => { const body = await input(context), expectedRevision = revision(body), channelId = context.params.channelId as ChannelId; if (typeof body.enabled !== 'boolean') throw new AppError(400, 'Invalid enabled'); const value = { operation: body.enabled ? 'enable' : 'disable', channelId, expectedRevision }; context.json(200, await service(context).setEnabled(await context.actor('write'), { projectId: context.params.projectId as ProjectId, channelId, expectedRevision, enabled: body.enabled, requestId: requestId(body), fingerprint: fingerprint(value) })) } },
  { method: 'POST', pattern: '/projects/:projectId/channel-bindings', auth: 'authenticated', handler: async context => { const body = await input(context), value = { operation: 'binding.create', channelId: body.channelId, externalConversationKey: body.externalConversationKey, sessionId: body.sessionId, callbackUrl: body.callbackUrl, senderAllowlist: body.senderAllowlist ?? [] }; context.json(201, await service(context).createBinding(await context.actor('write'), { projectId: context.params.projectId as ProjectId, channelId: String(body.channelId) as ChannelId, externalConversationKey: String(body.externalConversationKey ?? ''), sessionId: String(body.sessionId) as never, callbackUrl: String(body.callbackUrl ?? ''), senderAllowlist: strings(body.senderAllowlist ?? [], 'senderAllowlist'), requestId: requestId(body), fingerprint: fingerprint(value) })) } },
  { method: 'POST', pattern: '/projects/:projectId/channel-bindings/:bindingId/enabled', auth: 'authenticated', handler: async context => { const body = await input(context), expectedRevision = revision(body), bindingId = context.params.bindingId as ChannelBindingId; if (typeof body.enabled !== 'boolean') throw new AppError(400, 'Invalid enabled'); const value = { operation: body.enabled ? 'binding.enable' : 'binding.disable', bindingId, expectedRevision }; context.json(200, await service(context).setBindingEnabled(await context.actor('write'), { projectId: context.params.projectId as ProjectId, bindingId, expectedRevision, enabled: body.enabled, requestId: requestId(body), fingerprint: fingerprint(value) })) } },
  { method: 'POST', pattern: '/projects/:projectId/channel-deliveries/:deliveryId/replay', auth: 'authenticated', handler: async context => { const body = await input(context), reason = String(body.reason ?? ''), value = { operation: 'outbound.replay', deliveryId: context.params.deliveryId, reason }; context.json(200, await service(context).replay(await context.actor('write'), context.params.projectId as ProjectId, context.params.deliveryId, reason, { projectId: context.params.projectId as ProjectId, requestId: requestId(body), fingerprint: fingerprint(value) })) } },
]
