export const script = `let csrf='',capabilities=[],directories=[],sessions=[],currentSession='',fromSeq=1,eventSource=null,activeTurn='',clusterState=null;const q=s=>document.querySelector(s),login=q('#login'),status=q('#status'),error=q('#error'),workbenchError=q('#workbench-error'),sessionSelect=q('#session-select'),conversation=q('#conversation'),sessionEmpty=q('#session-empty'),timeline=q('#timeline'),runState=q('#run-state'),stopButton=q('#stop-turn'),sendButton=q('#send-message');const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));async function api(path,options={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),...(options.method&&options.method!=='GET'?{'x-wemux-csrf':csrf}:{})}});let data=null;try{data=response.status===204?null:await response.json()}catch{}if(!response.ok){if(response.status===401)showLogin();throw new Error(typeof data?.error==='string'?data.error:data?.error?.message||'请求失败')}return data}
function showLogin(){csrf='';generation++;eventSource?.close();eventSource=null;login.hidden=false;status.hidden=true}
function availableAgents(){return capabilities.filter(item=>item.mode==='execution'&&item.availability.status==='available'&&item.models.length)}
function renderCreationOptions(){const directorySelect=q('#session-form select[name=workspaceId]'),agentSelect=q('#session-form select[name=agentKey]'),modelSelect=q('#session-form select[name=modelId]'),createButton=q('#session-form button');const savedDirectory=directorySelect.value,savedAgent=agentSelect.value,savedModel=modelSelect.value;directorySelect.innerHTML=directories.length?directories.map(item=>'<option value="'+escapeHtml(item.workspaceId)+'">'+escapeHtml(item.name)+' · '+escapeHtml(item.path)+'</option>').join(''):'<option value="">请先添加目录</option>';const agents=availableAgents();agentSelect.innerHTML=agents.length?agents.map(item=>'<option value="'+escapeHtml(item.agentKey)+'">'+escapeHtml(item.displayName)+'</option>').join(''):'<option value="">没有可用 Agent</option>';if(directories.some(item=>item.workspaceId===savedDirectory))directorySelect.value=savedDirectory;if(agents.some(item=>item.agentKey===savedAgent))agentSelect.value=savedAgent;const selected=agents.find(item=>item.agentKey===agentSelect.value)||agents[0];modelSelect.innerHTML=selected?selected.models.map(model=>'<option value="'+escapeHtml(model.modelId)+'">'+escapeHtml(model.displayName)+'</option>').join(''):'<option value="">没有可用模型</option>';if(selected?.models.some(item=>item.modelId===savedModel))modelSelect.value=savedModel;directorySelect.disabled=!directories.length;agentSelect.disabled=!agents.length;modelSelect.disabled=!selected;createButton.disabled=!directories.length||!selected}
function sessionLabel(item){const directory=directories.find(entry=>entry.workspaceId===item.binding.workspaceId);const agent=capabilities.find(entry=>entry.agentKey===item.binding.agent.agentKey);return(directory?.name||'本地目录')+' · '+(agent?.displayName||item.binding.agent.agentKey)+' · '+item.binding.modelId}
function renderSessions(){sessionSelect.innerHTML=sessions.length?sessions.map(item=>'<option value="'+escapeHtml(item.sessionId)+'">'+escapeHtml(sessionLabel(item))+'</option>').join(''):'<option value="">暂无本地会话</option>';if(currentSession&&!sessions.some(item=>item.sessionId===currentSession))currentSession='';if(!currentSession&&sessions[0])currentSession=sessions[0].sessionId;sessionSelect.value=currentSession;const hasSession=Boolean(currentSession);sessionSelect.disabled=!hasSession;
q('#delete-session').disabled=!hasSession;conversation.hidden=!hasSession;sessionEmpty.hidden=hasSession;if(!hasSession){timeline.innerHTML='';setRunning(false)}}
function setRunning(running,turnId=''){activeTurn=running?turnId:'';runState.textContent=running?'智能体正在执行':'待命';stopButton.disabled=!running;sendButton.disabled=false}
function eventHtml(event){const p=event.payload;if(p.kind==='message.queued')return '<article class="event user"><strong>你</strong><p>'+escapeHtml(p.content)+'</p></article>';if(p.kind==='turn.started')return '<article class="event activity">智能体开始处理</article>';if(p.kind==='assistant.text.delta')return '<article class="event assistant" data-turn="'+escapeHtml(p.turnId)+'"><strong>智能体</strong><p>'+escapeHtml(p.text)+'</p></article>';if(p.kind==='tool.started')return '<article class="event tool"><strong>工具 · '+escapeHtml(p.toolName)+'</strong><pre>'+escapeHtml(JSON.stringify(p.input,null,2))+'</pre></article>';if(p.kind==='tool.output.delta')return '<article class="event tool"><strong>工具输出</strong><pre>'+escapeHtml(p.text)+'</pre></article>';if(p.kind==='tool.finished')return '<article class="event activity">工具结束'+(p.exitCode===null?'':'，退出码 '+escapeHtml(p.exitCode))+'</article>';if(p.kind==='approval.requested')return '<article class="event activity">运行等待批准</article>';if(p.kind==='approval.resolved')return '<article class="event activity">'+(p.decision==='approve'?'':'')+'</article>';if(p.kind==='usage.updated')return '';if(p.kind==='compaction.started')return '<article class="event activity">正在压缩会话上下文</article>';if(p.kind==='compaction.finished')return '<article class="event activity">会话上下文压缩完成</article>';if(p.kind==='message.cancelled')return '<article class="event activity">排队消息已取消</article>';if(p.kind==='session.runtime.changed')return '<article class="event activity">运行时状态：'+escapeHtml(p.state)+(p.reason?' · '+escapeHtml(p.reason):'')+'</article>';if(p.kind==='runtime.notice')return '<article class="event activity">'+escapeHtml(p.message)+'</article>';if(p.kind==='turn.finished'){const label=p.outcome==='completed'?'运行完成':p.outcome==='cancelled'?'运行已停止':'运行失败';return '<article class="event activity">'+label+(p.failure?' · '+escapeHtml(p.failure.message||p.failure.code||'未知错误'):'')+'</article>'}return ''}
function appendEvent(event){const p=event.payload;if(p.kind==='assistant.text.delta'){const selector='.event.assistant[data-turn="'+CSS.escape(String(p.turnId))+'"]';const existing=timeline.querySelector(selector);if(existing){existing.querySelector('p').textContent+=p.text}else{timeline.insertAdjacentHTML('beforeend',eventHtml(event))}}else{const html=eventHtml(event);if(html)timeline.insertAdjacentHTML('beforeend',html)}fromSeq=Math.max(fromSeq,event.seq+1);timeline.scrollTop=timeline.scrollHeight}
let generation=0,projection=new Map(),firstSeq=1,queueVersion=0;
const newId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
const pending=new Map();
async function mutate(path,payload){const key=path+JSON.stringify(payload);let body=pending.get(key);if(!body){body={...payload,commandId:newId(),messageId:newId(),requestId:newId()};pending.set(key,body)}const result=await api(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});pending.delete(key);return result}
const sessionPath=id=>'/api/local/workbench/sessions/'+encodeURIComponent(id);
function mergeEvents(events){const next=fromSeq;for(const event of events){if(event.sessionId!==currentSession||!Number.isSafeInteger(event.seq)||projection.has(event.seq))continue;projection.set(event.seq,event)}timeline.innerHTML='';const ordered=[...projection.values()].sort((a,b)=>a.seq-b.seq);for(const event of ordered)appendEvent(event);for(const event of ordered.filter(item=>item.seq>=next)){if(event.payload.kind==='turn.started')setRunning(true,event.payload.turnId);if(event.payload.kind==='turn.finished')setRunning(false)}firstSeq=ordered[0]?.seq||1;q('#load-older').hidden=firstSeq<=1;renderApprovals(ordered)}
const resolved=new Set();let pendingApprovals=[];
function renderApprovals(events){const container=q('#approvals');container.innerHTML='';for(const event of events)if(event.payload.kind==='approval.resolved')resolved.add(currentSession+':'+event.payload.approvalId);for(const p of pendingApprovals){if(p.turnId!==activeTurn||resolved.has(currentSession+':'+p.approvalId))continue;const article=document.createElement('article');article.className='event';const label=document.createElement('p');label.textContent=p.reason||JSON.stringify(p.action);article.append(label);for(const [decision,label] of [['approve','批准'],['deny','拒绝']]){const button=document.createElement('button');button.textContent=label;button.onclick=async()=>{const id=currentSession,g=generation;button.disabled=true;try{await mutate(sessionPath(id)+'/approvals/'+encodeURIComponent(p.approvalId)+'/resolve',{decision});resolved.add(id+':'+p.approvalId);if(g===generation)renderApprovals([...projection.values()])}catch(failure){if(g===generation){workbenchError.textContent=failure.message;button.disabled=false}}};article.append(button)}container.append(article)}}
async function refreshQueue(id=currentSession,g=generation){if(!id)return;const version=++queueVersion;const [queue,list,approvals]=await Promise.all([api(sessionPath(id)+'/queue'),api('/api/local/workbench/sessions'),api(sessionPath(id)+'/approvals')]);if(g!==generation||id!==currentSession||version!==queueVersion)return;pendingApprovals=approvals.items;const session=list.items.find(item=>item.sessionId===id);setRunning(Boolean(session?.activeTurnId),session?.activeTurnId||'');q('#queue').innerHTML='';for(const item of queue.items){const row=document.createElement('div'),label=document.createElement('span'),button=document.createElement('button');label.textContent=item.message.content;button.textContent='取消排队';button.className='secondary';button.onclick=async()=>{button.disabled=true;try{await api(sessionPath(id)+'/queue/'+encodeURIComponent(item.submissionCommandId)+'/cancel',{method:'DELETE'});if(g===generation)await refreshQueue(id,g)}catch(failure){if(g===generation){workbenchError.textContent=failure.message;button.disabled=false}}};row.append(label,button);q('#queue').append(row)}renderApprovals([...projection.values()])}
async function renderJournal(reset=false){if(!currentSession)return;const id=currentSession;if(reset){generation++;eventSource?.close();eventSource=null;projection=new Map();pendingApprovals=[];fromSeq=1;firstSeq=1;timeline.innerHTML='';q('#queue').innerHTML='';q('#approvals').innerHTML='';q('#compact').hidden=true;setRunning(false)}const g=generation;const page=await api(sessionPath(id)+'/journal?fromSeq='+(reset?0:fromSeq)+'&limit=200');if(g!==generation||id!==currentSession)return;mergeEvents(page.events);await refreshQueue(id,g);if(g!==generation)return;const commands=await api(sessionPath(id)+'/commands');if(g===generation)q('#compact').hidden=!commands.items.includes('compact')}
function connectEvents(){eventSource?.close();eventSource=null;if(!currentSession)return;const id=currentSession,g=generation;const stream=new EventSource(sessionPath(id)+'/events?fromSeq='+fromSeq);eventSource=stream;stream.addEventListener('journal',message=>{if(g!==generation||id!==currentSession||eventSource!==stream)return;try{mergeEvents([JSON.parse(message.data)]);refreshQueue(id,g).catch(failure=>{if(g===generation)workbenchError.textContent=failure.message})}catch{}});stream.addEventListener('auth-expired',()=>{if(g===generation)showLogin()});stream.onerror=()=>{if(g===generation)runState.textContent='实时连接恢复中'}}
async function openSession(){try{const promise=renderJournal(true),g=generation;await promise;if(g===generation)connectEvents()}catch(failure){workbenchError.textContent=failure.message}}
q('#load-older').onclick=async()=>{const id=currentSession,g=generation,before=firstSeq,button=q('#load-older');button.disabled=true;try{const start=Math.max(1,before-200);const page=await api(sessionPath(id)+'/journal?fromSeq='+start+'&limit='+(before-start));if(g===generation)mergeEvents(page.events)}catch(failure){if(g===generation)workbenchError.textContent=failure.message}finally{button.disabled=false}};
q('#compact').onclick=async()=>{const id=currentSession,g=generation;try{await mutate(sessionPath(id)+'/commands',{name:'compact'})}catch(failure){if(g===generation)workbenchError.textContent=failure.message}};
async function loadDirectories(){const data=await api('/api/local/workbench/directories');directories=data.items;renderCreationOptions()}
async function loadSessions(preferred=''){const g=generation;const data=await api('/api/local/workbench/sessions');if(g!==generation)return;sessions=data.items;if(preferred)currentSession=preferred;renderSessions();if(currentSession){await openSession()}else{generation++;eventSource?.close();eventSource=null}}
function renderCluster(){const enrolled=Boolean(clusterState?.enrolled),phase=clusterState?.connection?.phase||'offline',failure=clusterState?.connection?.failure||'';
q('#cluster').textContent=enrolled?'已加入 '+clusterState.serverUrl+' · '+phase:'未加入集群';
// 降级原因紧跟在集群状态下方：#cluster-error 在注册表单底下，首屏看不到，操作者只会看到“degraded”却不知道原因。
q('#cluster-notice').textContent=failure&&phase==='degraded'?failure:''
q('#enroll-form').hidden=enrolled;
q('#cluster-connect').disabled=!enrolled||phase==='online'||phase==='connecting';
q('#cluster-pause').disabled=!enrolled||phase==='offline';
q('#cluster-leave').disabled=!enrolled}
async function refreshStatus(){const data=await api('/api/local/status');csrf=data.csrf;capabilities=data.capabilities;clusterState=data.cluster;
q('#name').textContent=data.installation.name;
q('#installation').textContent=data.installation.installationId;renderCluster();const usable=availableAgents();
q('#agents').textContent=usable.length+' 个可执行，'+data.capabilities.length+' 项已检测';
q('#local').textContent=data.local.sessions+' 个会话，'+data.local.workspaces+' 个工作环境'}
async function load(){await refreshStatus();login.hidden=true;status.hidden=false;await loadDirectories();await loadSessions()}q('#login form').addEventListener('submit',async event=>{event.preventDefault();error.textContent='';const formElement=event.currentTarget,form=new FormData(formElement);try{const data=await api('/api/local/auth/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:form.get('username'),password:form.get('password')})});csrf=data.csrf;await load()}catch(failure){error.textContent=failure.message}});
q('#logout').addEventListener('click',async()=>{await api('/api/local/auth/session',{method:'DELETE'});location.reload()});
q('#enroll-form').addEventListener('submit',async event=>{event.preventDefault();const target=q('#cluster-error');target.textContent='';const formElement=event.currentTarget,form=new FormData(formElement),serverUrl=String(form.get('serverUrl')||'').trim();try{const discovered=await api('/api/local/cluster/discover',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverUrl})});if(!discovered.ok)throw new Error(discovered.error||'Server 探测失败（HTTP '+discovered.status+'）');await api('/api/local/cluster/enroll',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverUrl,token:form.get('token'),name:form.get('name')})});formElement.reset();await refreshStatus()}catch(failure){target.textContent=failure.message}});
q('#cluster-connect').addEventListener('click',async()=>{try{await api('/api/local/cluster/resume',{method:'POST'});await refreshStatus()}catch(failure){q('#cluster-error').textContent=failure.message}});
q('#cluster-pause').addEventListener('click',async()=>{try{await api('/api/local/cluster/pause',{method:'POST'});await refreshStatus()}catch(failure){q('#cluster-error').textContent=failure.message}});
q('#cluster-leave').addEventListener('click',async()=>{if(!confirm('退出集群并撤销本机保存的连接凭据？本地会话仍会保留。'))return;try{await api('/api/local/cluster/enrollment',{method:'DELETE'});await refreshStatus()}catch(failure){q('#cluster-error').textContent=failure.message}});
q('#session-form select[name=agentKey]').addEventListener('change',renderCreationOptions);
q('#directory-form').addEventListener('submit',async event=>{event.preventDefault();workbenchError.textContent='';const formElement=event.currentTarget,form=new FormData(formElement);try{await api('/api/local/workbench/directories',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path:form.get('path')})});formElement.reset();await loadDirectories()}catch(failure){workbenchError.textContent=failure.message}});
q('#session-form').addEventListener('submit',async event=>{event.preventDefault();workbenchError.textContent='';const formElement=event.currentTarget,form=new FormData(formElement);try{const created=await mutate('/api/local/workbench/sessions',{workspaceId:form.get('workspaceId'),agentKey:form.get('agentKey'),modelId:form.get('modelId')});await loadSessions(created.sessionId)}catch(failure){workbenchError.textContent=failure.message}});sessionSelect.addEventListener('change',async()=>{currentSession=sessionSelect.value;fromSeq=1;workbenchError.textContent='';await openSession()});
q('#delete-session').addEventListener('click',async()=>{if(!currentSession||!confirm('删除这个本地会话及其历史？'))return;workbenchError.textContent='';try{await api('/api/local/workbench/sessions/'+encodeURIComponent(currentSession),{method:'DELETE'});currentSession='';await loadSessions()}catch(failure){workbenchError.textContent=failure.message}});
q('#message-form').addEventListener('submit',async event=>{event.preventDefault();workbenchError.textContent='';if(!currentSession){workbenchError.textContent='请先新建会话';return}const formElement=event.currentTarget,form=new FormData(formElement),content=String(form.get('content')||'').trim();if(!content)return;const id=currentSession,g=generation;try{await mutate(sessionPath(id)+'/messages',{content});if(g===generation&&formElement.elements.content.value.trim()===content)formElement.reset();if(g===generation)await refreshQueue(id,g)}catch(failure){workbenchError.textContent=failure.message}});stopButton.addEventListener('click',async()=>{if(!currentSession||!activeTurn)return;workbenchError.textContent='';try{await api('/api/local/workbench/sessions/'+encodeURIComponent(currentSession)+'/turns/'+encodeURIComponent(activeTurn)+'/stop',{method:'POST'});await renderJournal()}catch(failure){workbenchError.textContent=failure.message}});addEventListener('beforeunload',()=>eventSource?.close());load().catch(failure=>{if(failure.message!=='Authentication required')error.textContent=failure.message});`
