import { useEffect, useRef, useState } from 'react'
import { AlertCircle, CheckCircle2, Copy, RefreshCw, RotateCcw, Webhook } from 'lucide-react'
import type { ChannelListDTO } from '@wemux/web-contract/channels'
import type { createApi } from '../../api/client.ts'
import type { SessionDTO } from '../../api/dto.ts'
import { randomId } from '../../lib/random.ts'
import { copyText, selectElementText } from '../../lib/utils.ts'
import { Button } from '../../components/ui/button.tsx'
import { Input } from '../../components/ui/input.tsx'

export function ChannelPage({ api, projectId, sessions, canManage }: { api: ReturnType<typeof createApi>; projectId: string; sessions: SessionDTO[]; canManage: boolean }) {
  const [data, setData] = useState<ChannelListDTO>({ items: [], bindings: [], inbound: [], outbound: [] })
  const [kind, setKind] = useState<'generic_webhook' | 'feishu'>('generic_webhook'), [name, setName] = useState('Generic Webhook'), [conversation, setConversation] = useState('default'), [callbackUrl, setCallbackUrl] = useState(''), [sessionId, setSessionId] = useState('')
  const [appId, setAppId] = useState(''), [appSecret, setAppSecret] = useState(''), [verificationToken, setVerificationToken] = useState(''), [encryptKey, setEncryptKey] = useState('')
  const [issuedToken, setIssuedToken] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState('')
  const tokenRef = useRef<HTMLElement>(null)
  const load = async () => { setError(''); try { setData(await api.channels(projectId)) } catch (cause) { setError(message(cause, '加载 Channel 失败')) } }
  useEffect(() => { void load() }, [projectId])
  useEffect(() => { if (!sessionId && sessions[0]) setSessionId(sessions[0].id) }, [sessions, sessionId])
  const create = async () => { setBusy('create'); setError(''); setNotice(''); try { const result = await api.createChannel(projectId, kind === 'feishu' ? { requestId: randomId(), kind, name, appId, appSecret, verificationToken, encryptKey: encryptKey.trim() || null } : { requestId: randomId(), kind, name, callbackUrl: null, sourceCidrs: [] }); setIssuedToken(result.issuedToken ?? ''); setNotice(kind === 'feishu' ? '飞书 Channel 已创建。请把事件订阅 URL 配置到飞书开放平台。' : 'Channel 已创建。令牌仅显示一次，请立即保存。'); await load() } catch (cause) { setError(message(cause, '创建 Channel 失败')) } finally { setBusy('') } }
  const bind = async () => { const channel = data.items[0]; if (!channel || !sessionId || (channel.kind === 'generic_webhook' && !callbackUrl)) { setError('请选择 Channel、Session，并为 Generic Webhook 填写回调 URL。'); return } setBusy('bind'); setError(''); try { await api.createChannelBinding(projectId, { requestId: randomId(), channelId: channel.id, externalConversationKey: conversation, sessionId, callbackUrl, senderAllowlist: [] }); setNotice('Binding 已创建。'); await load() } catch (cause) { setError(message(cause, '创建 binding 失败')) } finally { setBusy('') } }
  const toggle = async (item: ChannelListDTO['items'][number]) => { setBusy(`channel:${item.id}`); try { await api.setChannelEnabled(projectId, item.id, { requestId: randomId(), expectedRevision: item.revision, enabled: !item.enabled }); await load() } catch (cause) { setError(message(cause, '更新 Channel 状态失败')) } finally { setBusy('') } }
  const testConnection = async (id: string) => { setBusy(`test:${id}`); setError(''); try { await api.testFeishuChannel(projectId, id); setNotice('飞书连接测试成功：tenant_access_token 已获取。') } catch (cause) { setError(message(cause, '飞书连接测试失败')) } finally { setBusy('') } }
  const replay = async (id: string) => { setBusy(`replay:${id}`); try { await api.replayChannelDelivery(projectId, id, { requestId: randomId(), reason: '诊断页手工重放' }); await load() } catch (cause) { setError(message(cause, '重放失败')) } finally { setBusy('') } }
  const copy = async () => { if (await copyText(issuedToken)) { setNotice('令牌已复制。'); return } if (tokenRef.current) selectElementText(tokenRef.current); setNotice('浏览器未允许自动复制，已选中令牌，请按 Ctrl+C 或长按复制。') }
  const origin = typeof window === 'undefined' ? '' : window.location.origin
  return <div className="space-y-5"><header className="flex items-start justify-between gap-3 border-b border-border pb-3"><div><h1 className="flex items-center gap-2 text-base font-semibold"><Webhook className="size-4" />Channel</h1><p className="mt-1 text-xs text-muted-foreground">Generic webhook 入站、Session binding 与回复投递诊断。</p></div><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCw className="size-3.5" />刷新</Button></header>
    {error && <p role="alert" className="flex items-center gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300"><AlertCircle className="size-4" />{error}</p>}{notice && <p role="status" className="flex items-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm"><CheckCircle2 className="size-4" />{notice}</p>}
    {issuedToken && <section className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4"><h2 className="text-sm font-medium">一次性 Channel 令牌</h2><code ref={tokenRef} className="mt-2 block select-all break-all rounded bg-background p-3 text-xs">{issuedToken}</code><Button className="mt-3" size="sm" variant="outline" onClick={() => void copy()}><Copy className="size-3.5" />复制令牌</Button></section>}
    {canManage && <section className="grid gap-4 rounded-xl border border-border bg-card p-4 lg:grid-cols-2"><div className="space-y-3"><h2 className="text-sm font-medium">创建 Channel</h2><label className="grid gap-1 text-xs">类型<select className="h-9 rounded-md border border-input bg-background px-3" value={kind} onChange={event => { const value = event.target.value as typeof kind; setKind(value); setName(value === 'feishu' ? '飞书机器人' : 'Generic Webhook') }}><option value="generic_webhook">Generic Webhook</option><option value="feishu">飞书应用机器人</option></select></label><label className="grid gap-1 text-xs">名称<Input value={name} onChange={event => setName(event.target.value)} /></label>{kind === 'feishu' && <><label className="grid gap-1 text-xs">App ID<Input value={appId} onChange={event => setAppId(event.target.value)} /></label><label className="grid gap-1 text-xs">App Secret<Input type="password" value={appSecret} onChange={event => setAppSecret(event.target.value)} /></label><label className="grid gap-1 text-xs">Verification Token<Input type="password" value={verificationToken} onChange={event => setVerificationToken(event.target.value)} /></label><label className="grid gap-1 text-xs">Encrypt Key（可选）<Input type="password" value={encryptKey} onChange={event => setEncryptKey(event.target.value)} /></label></>}<Button disabled={busy === 'create'} onClick={() => void create()}>{kind === 'feishu' ? '保存飞书配置' : '创建并签发令牌'}</Button></div><div className="space-y-3"><h2 className="text-sm font-medium">创建 binding</h2><label className="grid gap-1 text-xs">外部会话键<Input value={conversation} onChange={event => setConversation(event.target.value)} /></label><label className="grid gap-1 text-xs">目标 Session<select className="h-9 rounded-md border border-input bg-background px-3" value={sessionId} onChange={event => setSessionId(event.target.value)}>{sessions.map(session => <option key={session.id} value={session.id}>{session.title}</option>)}</select></label><label className="grid gap-1 text-xs">回复回调 URL（飞书无需填写）<Input value={callbackUrl} placeholder="https://receiver.example.com/webhook" onChange={event => setCallbackUrl(event.target.value)} /></label><Button disabled={busy === 'bind'} onClick={() => void bind()}>保存 binding</Button></div></section>}
    <section className="space-y-3"><h2 className="text-sm font-medium">Channel 列表</h2>{data.items.map(item => <article key={item.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.kind === 'feishu' ? '事件订阅 URL' : 'Webhook URL'}：{origin}{item.webhookPath}</p><p className="text-xs text-muted-foreground">{item.kind === 'feishu' ? `${item.appIdHint} · schema ${item.acceptEventSchema} · ${item.verificationMode}` : `token v${item.tokenVersion}`} · revision {item.revision}</p></div>{canManage && <div className="flex gap-2">{item.kind === 'feishu' && <Button size="sm" variant="outline" disabled={busy === `test:${item.id}`} onClick={() => void testConnection(item.id)}>连接测试</Button>}<Button size="sm" variant="outline" disabled={busy === `channel:${item.id}`} onClick={() => void toggle(item)}>{item.enabled ? '停用' : '启用'}</Button></div>}</div></article>)}{!data.items.length && <p className="text-sm text-muted-foreground">暂无 Channel。</p>}</section>
    <section className="space-y-3"><h2 className="text-sm font-medium">Binding</h2>{data.bindings.map(item => <article key={item.id} className="rounded-lg border border-border p-3 text-xs"><p>{item.externalConversationKey} → {sessions.find(session => session.id === item.sessionId)?.title ?? item.sessionId}</p><p className="mt-1 break-all text-muted-foreground">{item.callbackUrl} · {item.enabled ? '已启用' : '已停用'}</p></article>)}</section>
    <section className="space-y-3"><h2 className="text-sm font-medium">Delivery 诊断</h2>{data.inbound.map(item => <article key={item.id} className="rounded-lg border border-border p-3 text-xs"><p>入站 {item.status} · {item.identityStrength}</p><p className="text-muted-foreground">{item.externalConversationKey} · {item.diagnostic ?? '无诊断'}</p></article>)}{data.outbound.map(item => <article key={item.id} className="flex items-center gap-3 rounded-lg border border-border p-3 text-xs"><div className="min-w-0 flex-1"><p>出站 {item.status} · 尝试 {item.attempt}/6</p><p className="truncate text-muted-foreground">{item.diagnostic ?? '无诊断'}</p></div>{canManage && (item.status === 'dead_letter' || item.status === 'cancelled') && <Button size="sm" variant="outline" disabled={busy === `replay:${item.id}`} onClick={() => void replay(item.id)}><RotateCcw className="size-3.5" />重放</Button>}</article>)}{!data.inbound.length && !data.outbound.length && <p className="text-sm text-muted-foreground">暂无投递记录。</p>}</section>
  </div>
}
function message(cause: unknown, fallback: string): string { return cause instanceof Error ? cause.message : fallback }
